modLoader = "kotlinforforge"
loaderVersion = "${loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/EchoEllet/dragonfist-legacy/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "DragonFist Legacy"
displayURL = "https://github.com/EchoEllet/dragonfist-legacy/"
credits = "https://github.com/EchoEllet/dragonfist-legacy/blob/main/CREDITS.md"
authors = "EchoEllet"
description = '''An Epic Fight addon, adding Shifu, bandits and more to fight and explore!'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "epicfight"
type = "optional"
mandatory = false
versionRange = "${epicfight_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "epicskills"
type = "optional"
mandatory = false
versionRange = "${epicskills_version_range}"
ordering = "NONE"
side = "BOTH"
